# Generated by Django 2.0.7 on 2018-10-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
